[versions]
compose = "1.1.0-beta03"
ktlint = "0.43.0"
dokka = "1.5.0"
kotlin = "1.5.31"
coroutines = "1.5.2"

[libraries]
agp = "com.android.tools.build:gradle:7.1.2"
kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-binaryvalidator = "org.jetbrains.kotlinx:binary-compatibility-validator:0.6.0"
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

androidx-core = "androidx.core:core-ktx:1.7.0"
androidx-lifecycle = "androidx.lifecycle:lifecycle-runtime-ktx:2.4.0"
androidx-activity-compose = "androidx.activity:activity-compose:1.4.0"

compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-materialicons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-ui-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-toolingpreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-ui-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
compose-paging = "androidx.paging:paging-compose:1.0.0-alpha12"

spotless = "com.diffplug.spotless:spotless-plugin-gradle:5.11.0"

dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
nexus-publish = "io.github.gradle-nexus:publish-plugin:1.1.0"
gradle-dependency-updates = "com.github.ben-manes:gradle-versions-plugin:0.39.0"

# Tests
junit = "junit:junit:4.+"
androidx-junit = "androidx.test.ext:junit:1.1.3"
androidx-espresso = "androidx.test.espresso:espresso-core:3.4.0"
androidx-test-runner = "androidx.test:runner:1.4.0"
androidx-test-orchestrator = "androidx.test:orchestrator:1.4.0"
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
turbine = "app.cash.turbine:turbine:0.7.0"
